### ISSUE TITLE
Criar autenticação por models.

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#102]
**Descreva a solução que gostaria**

Fazer autenticação por models 

**Funcionalidades requeridas**

- [ ] Realizar a autenticação utilizando o graphql-jwt nas funções resolve
- [ ] Criar permissão para usuários administradores do sistema.

**Comment by higton** [comment]
@AlineLermen conseguiu implementar os decorators?

**Comment by AlineLermen** [comment]
Ainda não. Estou trabalhando nisso

**Comment by higton** [comment]
Não consegui implementar o @permission_required, vou continuar dando uma olhada nisso.

**Comment by higton** [comment]
Para terminar a issue só falta colocar a senha no bot
