### ISSUE TITLE
Empacotar o sistema de autenticação

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#104]
**Descreva a solução que gostaria **

Criar um pacote python com o sistema de autenticação de voz.

**Funcionalidades requeridas**

- [x] Criar pacote de acordo com o padrão do pypi
- [x] Adicionar todas as informações no arquivo setup.py

**Comment by VictorJorgeFGA** [comment]
Link do pacote:
https://pypi.org/project/speaker-verification-tools/#description

Repo do pacote:
https://github.com/VictorJorgeFGA/speaker-verification-tools

Caso não precise de mais nada, pode fechar a issue.

**Comment by VictorJorgeFGA** [comment]
Repo contendo os sources do package:
https://github.com/Alohomora-team/speaker-verification-toolkit

Package no PyPI:
https://pypi.org/project/speaker-verification-toolkit/0.0.1/
