### ISSUE TITLE
Desacoplar o código do bot

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#105]
**Descreva a solução que gostaria**

Separar o script do bot em arquivos e realizar os testes unitários.

**Funcionalidades requeridas**

- [ ] Separar o script principal em vários arquivos (pacotes concisos)
- [ ] Realizar os testes unitários
- [ ] Atualizar o CHANGELOG
- [ ] Criar arquivos de constantes

**Comment by higton** [comment]
@luis-furtado vou focar nas partes do testes unitários.

**Comment by higton** [comment]
@Bumbleblo não estou conseguindo utilizar $docker-compose run bot test, oque eu preciso fazer para rodar os testes no bot?

**Comment by luis-furtado** [comment]
Estou no processo de desmembramento dos códigos em classes no momento mas por enquanto ainda só na parte de registro

**Comment by Bumbleblo** [comment]
@higton mostre a mensagem por favor.

**Comment by luis-furtado** [comment]
@Bumbleblo @BordaLorde @mateusnr  estou com um problema na comunicação do Bot. Toda vez que o bot envia uma query ou mutation o sistema congela. Busquei informação com alguns colegas mas nenhum deles conseguiu encontrar o problema.

O novo código do Bot encontra-se na branch `desacoplar_codigo_bot` e está rodando (o token do Bot pertence ao bot fake @AlohomoraTestBot), só trava quando precisa enviar uma mutation no final com os dados do cadastrado.

Obs: Verificamos que a API estava funcionando perfeitamente na hora das requisições e mesmo assim resultaram em erro.

Se puderem analisar o código ou até mesmo dar um `push` pra testarem localmente e verificarem o erro ficaria grato.

**Comment by Bumbleblo** [comment]
Vou verificar, da próxima vez cria a branch com o código da issue.

**Comment by Bumbleblo** [comment]
@luis-furtado nós depreciamos o código do bot presente no repositório alohomora. Estamos utilizando o [AlohomoraBot](https://github.com/Alohomora-team/2019.2-AlohomoraBot). Desculpe não ter retirado o código antes, tivemos que realizar a alteração para que o deploy não ficasse prejudicado.

**Comment by higton** [comment]
> @higton mostre a mensagem por favor.

Aparece nenhuma mensagem de error, pois o comando não está reconhecendo o tests.py.

**Comment by higton** [comment]
Consegui fazer aqui, era só utilizar o $docker-compose run bot python test.py
