### ISSUE TITLE
Extração da parte útil do áudio

### ISSUE THREAD

**Issue by VictorJorgeFGA** [fga-eps-mds/2019.2-Alohomora#115]
**Descreva a solução que gostaria**

Boa parte dos áudios carregam trechos silenciosos que geralmente aparecem: antes do usuários começarem a falar, durante a fala (pausas desnecessárias) e depois de falar. Esses trechos silenciosos aumentam o tamanho do dado e acarretam na degradação do algoritmo de reconhecimento.

**Funcionalidades requeridas**

- [ ] Pesquisar e implementar algoritmos/sistemas que cortem fora as partes silenciosas do áudio.

- [ ] Adicionar a funcionalidade no package de autenticação do projeto.

**Comment by Bumbleblo** [comment]
Coloque essa issue no repositório de autenticação. https://github.com/Alohomora-team/VoiceAuthentication

**Comment by Bumbleblo** [comment]
Essa issue esta em: https://github.com/Alohomora-team/VoiceAuthentication/issues/1
