### ISSUE TITLE
Escrever EAP

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#14]
Elaboração da Estrutura Analítica do Projeto

### Tarefas

- [x] Criar documento no drive
- [x] Adicionar estrutura básica ao documento
- [x] Reunir com EPS pra levantar os dados
- [x] Revisão do documento
- [ ] Passar documento para o GHPages

**Comment by Bumbleblo** [comment]
@mateusnr descreva a issue por favor.

**Comment by Bumbleblo** [comment]
@mateusnr coloca o link do drive aqui com permissão de leitura

**Comment by mateusnr** [comment]
Link da EAP somente leitura: https://drive.google.com/file/d/1x9MBwX_xx5mSGdaBXESpLFPgBvDOyyYW/view
