### ISSUE TITLE
Criar a Query do DTW na API

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#59]
**Descreva a solução que gostaria**

Criar a Query na API que faça a autenticação por voz via DTW.

**Funcionalidades requeridas**

- [x] Criar a Query relacionando o tipo usuário no graphql
- [ ] Realizar testes na aplicação
- [x] Integrar o algoritmo na Query.

**Comment by Bumbleblo** [comment]
Como esta o progresso deste trabalho ?

**Comment by RodrigoTCLima** [comment]
O código do DTW gera uma matriz, como eu colocaria isso de forma prática no código?

**Comment by VictorJorgeFGA** [comment]
A Issue finalmente está andando. A única coisa que ainda está incerta são os parâmetros da query. Na ideia atual a Aline precisaria abrir o arquivo de audio que ela captura do usuário e enviar o vetor de dados no próprio graphql. O problema é que o arquivo não é em formato .wav ( dificultando a abertura ) e também o vetor precisa ser unidimensional.

**Comment by VictorJorgeFGA** [comment]
Atualmente a ideia da query é ser algo do tipo:

`
{
    voiceBelongsUser( cpf: $cpf , voice_data: $data_vector )
}
`
O field voiceBelongsUser vai retornar um simples booleano.
