### ISSUE TITLE
Escrever interação de autenticação do usuário

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#61]
**Descreva a solução que gostaria **

Criar a interação no bot que recolha a voz do usuário e use a autenticação por voz provida na API para autenticar o mesmo.

**Funcionalidades requeridas**

- [ ] Adicionar a interação citada no bot.
- [ ] Testar a aplicação

**Comment by AlineLermen** [comment]
Na issue #58 comentei sobre a mensagem de áudio que o usuário envia e sobre o arquivo de áudio resultante dela, incluindo a conversão do mesmo. Acredito que tudo isso se aplique também nessa issue aqui.

**Comment by Bumbleblo** [comment]
Essa issue já foi terminada ?

**Comment by AlineLermen** [comment]
Vou abrir o PR hoje
