### ISSUE TITLE
Alterar autenticação de usuários para autenticação de serviços

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#62]
**Descreva a solução que gostaria**

Atualmente a autenticação da API é realizada através de token para usuários. Porém essa abordagem traz vários problemas de segurança para a aplicação (usuários criando blocos).

**Funcionalidades requeridas**

-  [x] Apenas mudar a avaliação da autenticação
- [ ] Testar a funcionalidade

**Contexto Adicional**
Adicionem outros contextos e fotos das telas

**Comment by Bumbleblo** [comment]
Como esta o progresso deste trabalho ?

**Comment by higton** [comment]
Fiz a mudança, mas ainda falta os testes.
