### ISSUE TITLE
Criar apresentação do sistema

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#86]
**Descreva a solução que gostaria**

Criar apresentação para demonstrar o funcionamento do sistema e os principais objetivos.

**Funcionalidades requeridas**

- [x] Criar apresentação
- [x] Montar a demo do projeto

**Comment by Bumbleblo** [comment]
Coloquem aqui o link também pessoal

**Comment by AlineLermen** [comment]
Apresentação no [drive](https://docs.google.com/presentation/d/1Stq0aMrGHJtB4bNKjKWnblM6ARlbEPcDAjC2B-zUUU0/edit?usp=sharing)
