### ISSUE TITLE
Ajustes na API para R1

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#89]
**Descreva a solução que gostaria**

Ajustar as chaves da API adicionar variáveis de ambiente. Padronizar testes da API e organizar os comentários do código.

**Funcionalidades requeridas**

- [ ] Adicionar variáveis de ambiente 
- [ ] Esconder secret-key
- [ ] Padronizar comentários e testes

**Comment by higton** [comment]
Como você quer que seja feita essa parte de esconder a secret-key?
A parte de adicionar variáves de ambiente eu ainda não entendi, se você puder explicar melhor eu agradeceria.

**Comment by Bumbleblo** [comment]
Essa parte eu ou o @BordaLorde que vai fazer. No momento concentra na parte da padronização

**Comment by higton** [comment]
Eu me lembro de você ter falado no dojo sobre comentar as classes, seria bom se você pudesse comentar mais sobre isso.

**Comment by Bumbleblo** [comment]
Praticamente colocar as docstrings como é especificado na pep8

**Comment by Bumbleblo** [comment]
Posso adicionar essa regra no pylint
